name: numerical_collection
version: 0.1.3
description: Simple collection to work with numbers.
author: Graciliano Monteiro Passos <gracilianomp@gmail.com>
homepage: https://github.com/UpLibs/numerical_collection
